version: "3.8"

services:
  app:
    build:
      context: .
      target: ${ENV:-prod}
    ports:
      - "3000:80"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=${NODE_ENV:-production}
